baseURL = "https://fatratkiller.github.io/" # Replace with your domain
languageCode = "en-us"
theme = "smigle"
title = "Fatratkiller Blog"

[menu]
  [[menu.main]] # Change menu as needed
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 2
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 3
  [[menu.main]]
    identifier = "categories"
    name = "Categories"
    url = "/categories/"
    weight = 4
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 5


[params]
abbrDateFmt = "Jan 2"
author = "Blog Author"
brandIconFile = "images/brandIcon.svg"
dateFmt = "2006-01-02"
# Options for overriding theme or page defaults
# customStylesheets = ["css/custom.css"] # Use to override theme styles, like logo size
# readingSpeed = 600 # Use to set custom reading speed
# readingSpeedMin = 25 # Use to set custom reading speed range
# readingSpeedMax = 175 # Use to set custom reading speed range

[[params.social]]
name = "GitHub"
url = "https://github.com/fatratkiller"

[[params.social]]
name = "LinkedIn"
url = "https://www.linkedin.com/in/kyle-leo-53a40324a/"

[[params.social]]
name = "Twitter"
url = "https://twitter.com/FatRatKiller"

subtitle = "Man once lived in hell,Passive Income,Full-Stack Developer,Web3 Geek,Crypto Investment"
